name: creating s3 bucket with terraform
run-name: ${{ github.event.head_commit.message }}
on:
    push:
        branches:
            - main
        paths:
            - 'AWS-S3/**'
jobs:
     create-s3-bucket:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: AWS-S3

        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.12.2
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-south-1
            - name: terraform init
              run: terraform init
            - name: terraform plan
              run: terraform plan -var="bucket_name=manoj8008bucket" -var="aws_region=ap-south-1" -out=tfplan
            - name: terraform apply
              run: terraform apply tfplan              